# Final, cleaned netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

# Global settings for your lightweight API proxy functions
[functions]
  node_bundler = "esbuild" # Switched back to the faster default bundler