[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  # Switch the bundler from esbuild to zisi
  node_bundler = "zisi"
  # Keep this line to ensure the browser files are included
  included_files = ["node_modules/@sparticuz/chromium/**"]

# These settings apply to all functions
[functions."*"]
  timeout = 30
  memory = 1024