[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"
  included_files = ["node_modules/@sparticuz/chromium/**"]

# This schedule now runs the new function every 5 minutes
[[functions.schedule]]
  cron = "*/5 * * * *"
  function = "scrape-category-by-schedule"

[functions."*"]
  timeout = 240 # 4 minutes, well within the 5-minute window
  memory = 1024