[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # This line tells Netlify to include the browser files in the deployment.
  included_files = ["node_modules/@sparticuz/chromium/**"]

# These settings apply to all functions
[functions."*"]
  timeout = 30
  memory = 1024