# Final netlify.toml

[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# This section schedules your scraper to run every 5 minutes
[functions."scrape-category-by-schedule"]
  schedule = "0 * * * *"