[build]
  publish = "."
  functions = "netlify/functions"

# This section schedules ONE specific function
[[functions]]
  function = "scrape-category-by-schedule"
  schedule = "*/5 * * * *"

# This section applies global settings to ALL functions
[functions."*"]
  node_bundler = "zisi"
  included_files = ["node_modules/@sparticuz/chromium/**"]
  timeout = 240 # 4 minutes
  memory = 1024